sonar.projectKey=Space2Study-UA-4427-4288-01-2_Client-01
sonar.organization=space2study-ua-4427-4288-01-2

sonar.projectName=Client-01

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=./src
sonar.exclusions=**/src/tests/**/*, **/src/assets/**/*, **/build-story/*
sonar.coverage.exclusions=**/src/constants/*, **/*.styles.ts

sonar.tests=./src/tests

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Exclude test subdirectories from source scope
sonar.javascript.lcov.reportPaths=./src/tests/coverage/lcov.info
sonar.testExecutionReportPaths=./test-report.xml
#sonar.eslint.reportPaths
